### ISSUE TITLE
Error installing mapbox-tilesets using  "pip install mapbox-tilesets" on Windows 10 with Python 3.9.1

### ISSUE THREAD

**Issue by anonymouskeyboard47** [mapbox/tilesets-cli#118]
Hi,

I tried installing mapbox-tilesets using the command "pip install mapbox-tilesets" but the following errors arose. I am running the command using Administrator privileges. Below is the error log. Is there something I am missing?

Thanks in advance

ERROR: Command errored out with exit status 1:
   command: 'c:\users\jamof\appdata\local\programs\python\python39\python.exe' 'c:\users\jamof\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\jamof\AppData\Local\Temp\tmpiv9q0dkr'
       cwd: C:\Users\jamof\AppData\Local\Temp\pip-install-qce0pbgo\rasterio_5ae10d2ecf764959aff9379cb236e171
  Complete output (22 lines):
  Traceback (most recent call last):
    File "c:\users\jamof\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "c:\users\jamof\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\users\jamof\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\jamof\AppData\Local\Temp\pip-build-env-kfcjvtxh\overlay\Lib\site-packages\setuptools\build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\jamof\AppData\Local\Temp\pip-build-env-kfcjvtxh\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "C:\Users\jamof\AppData\Local\Temp\pip-build-env-kfcjvtxh\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\jamof\AppData\Local\Temp\pip-build-env-kfcjvtxh\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 89, in <module>
      import numpy as np
    File "C:\Users\jamof\AppData\Local\Temp\pip-build-env-kfcjvtxh\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
      _win_os_check()
    File "C:\Users\jamof\AppData\Local\Temp\pip-build-env-kfcjvtxh\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
      raise RuntimeError(msg.format(__file__)) from None
  RuntimeError: The current Numpy installation ('C:\\Users\\jamof\\AppData\\Local\\Temp\\pip-build-env-kfcjvtxh\\overlay\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\jamof\appdata\local\programs\python\python39\python.exe' 'c:\users\jamof\appdata\local\programs\python\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\jamof\AppData\Local\Temp\tmpiv9q0dkr' Check the logs for full command output.

**Comment by anonymouskeyboard47** [comment]
The problem comes when installing rasterio.

**Comment by 32Vache** [comment]
same

**Comment by tapczan1337** [comment]
In case someone stumbles onto this problem here's how I solved it.
Let me preface it that I'm fresh when it comes to this, so I might recommend a lot of unnecessary steps. You're welcome to correct me.

- First of all install [Anaconda for Windows](https://repo.anaconda.com/archive/Anaconda3-2021.05-Windows-x86_64.exe);
- Run Anaconda as admin;
- create new virtual environment via `conda create --name yourName` command;
- activate created environment: `activate yourName`;
- run `conda install -c conda-forge rasterio` command.

If it works great, you can now proceed with `pip install mapbox-tilesets`. If it stucks on 'Solving environment' like in my case try:

- download [GDAL ](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal) library (be careful with versioning. p39 means Python 3.9. It must match Python version installed on your machine);
- likewise install [Rasterio ](https://www.lfd.uci.edu/~gohlke/pythonlibs/#rasterio) lib;
- now run following commands in Anaconda: `pip install -U pip`, then `pip install pathToFile\yourGDAL.whl`, then `pip install pathToFile\yourRasterio4.whl`
- finally it came to executing dreaded `pip install mapbox-tilesets`. It is (hopefully) all done.

As a side note if you wish to store your mapbox access token as an environment variable the correct Windows command is:
`set MAPBOX_ACCESS_TOKEN=<YOUR_MAPBOX_ACCESS_TOKEN>`, not
`export MAPBOX_ACCESS_TOKEN=<YOUR_MAPBOX_ACCESS_TOKEN>`

**Comment by joegasewicz** [comment]
Errors out  on Mac Monterey but does eventually install the `rasterio` package.
```
  ERROR: Command errored out with exit status 1:
   command: /Users/josefgasewicz/Study/map/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/31/16hjxyv54nlf_n_lsb6yxhcr0000gn/T/pip-install-oiybx8zy/rasterio_9d106abad69943fe9e9536090d378958/setup.py'"'"'; __file__='"'"'/private/var/folders/31/16hjxyv54nlf_n_lsb6yxhcr0000gn/T/pip-install-oiybx8zy/rasterio_9d106abad69943fe9e9536090d378958/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/31/16hjxyv54nlf_n_lsb6yxhcr0000gn/T/pip-pip-egg-info-y77up5_n
       cwd: /private/var/folders/31/16hjxyv54nlf_n_lsb6yxhcr0000gn/T/pip-install-oiybx8zy/rasterio_9d106abad69943fe9e9536090d378958/
  Complete output (1 lines):
  CRITICAL:root:Numpy and its headers are required to run setup(). Exiting.```

**Comment by meganluisa** [comment]
Closing issue since this problem can now be resolved with the Windows installation requirements per the README.
